name: Test Suite

on:
  push:
    branches-ignore:
      - "develop"
      - "main"
  pull_request:
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
